<!-- File autogenerated by the Paraglide-SvelteKit CLI - Feel free to edit -->
<script>
	import { ParaglideJS } from '@inlang/paraglide-sveltekit'
	import { i18n } from '$lib/i18n'
  import * as m from '$lib/paraglide/messages.js';
  import 'inter-ui/inter-variable.css';

  const { children } = $props();
</script>

<svelte:head>
  <title>
    {m.mainTitle()}
  </title>
</svelte:head>

<ParaglideJS {i18n}>
  {@render children()}
</ParaglideJS>