<!-- File autogenerated by the Paraglide-SvelteKit CLI - Feel free to edit -->
<script>
	import { ParaglideJS } from '@inlang/paraglide-sveltekit';
	import { i18n } from '$lib/i18n';
  import * as m from '$lib/paraglide/messages.js';
  import 'inter-ui/inter-variable.css';

  import Header from '$lib/controls/Header/Header.svelte';
  import Footer from '$lib/controls/Footer/Footer.svelte';

  const { children } = $props();
</script>

<svelte:head>
  <title>
    {m.mainTitle()}
  </title>
</svelte:head>

<style>
  .layout {
    display: grid;
    grid-template-columns: 1fr;
    grid-auto-flow: row;
    grid-template-rows: max-content 1fr max-content;
    grid-template-areas:
      'header'
      'main'
      'footer'
    ;
    gap: var(--main-grid-gap);
    min-height: 100svh;

    container-name: layout;
  }
  header {
    grid-area: header;
    /* top: 0; */

    container-name: header;
  }
  main {
    grid-area: main;
    display: grid;

    container-name: main;
  }
  footer {
    grid-area: footer;
    /* bottom: 0; */

    container-name: footer;
  }

  header, footer {
    display: grid;
    /* position: sticky; */
  }

  .layout, header, main, footer {
    container-type: inline-size;
  }
</style>

<ParaglideJS {i18n}>
  <div class="layout">
    <header>
      <Header />
    </header>
    <main>
      {@render children()}
    </main>
    <footer>
      <Footer />
    </footer>
  </div>
</ParaglideJS>