# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-os:
    runs-on: ubuntu-24.04
    steps:
    - name: Update OS
      run: sudo apt-get update
  
  run-unit-tests:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [22.8.0]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4 
        with:
          version: 9.9.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm --recursive install
      - run: pnpm --recursive run specs
      - run: pnpm --recursive run cover